name: cek_cuaca
description: "A new Flutter project by Jeriko, assisted by Yanto."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paket yang kita tambahkan
  http: ^1.2.1
  weather_icons: ^3.0.0


  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# Bagian ini adalah konfigurasi khusus Flutter.
flutter:

  # Baris ini mengaktifkan penggunaan ikon-ikon Material Design.
  uses-material-design: true

  # Bagian ini untuk mendaftarkan aset gambar kita.
  # Pastikan 'assets:' sejajar dengan 'uses-material-design:'.
  assets:
    # Baris ini harus ada dua spasi di depannya.
    - assets/images/